server:
  port: 8004

spring:
  application:
    name: service-cms
  profiles:
    active: dev
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss            # springmvc对日期字符串的自动转换格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss            # 响应结果日期格式转换
    time-zone: GMT+8

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1                       # 表示已经删除
      logic-not-delete-value: 0                   # 表示未删除
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: service-cms:8004
    prefer-ip-address: true

# ribbon超时时间
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-init-sql: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
  redis:
    host: 192.168.24.128
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0