server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件的大小
      max-file-size: 1024MB
      # 请求上传最大数据大小
      max-request-size: 1024MB

eureka:
  client:
    # 表示将自己注册经EurekaServer
    register-with-eureka: true
    # 是否从EurekaServer上抓取已有的注册信息，默认为true,集群时必须设置为true
    fetch-registry: true
    service-url:
      # 同时将服务注册到注册中心集群中
      defaultZone: http://localhost:8000/eureka
  instance:
    # 服务在注册中心的主机名
    instance-id: service-vod:8003
    # 访问路径显示IP地址
    prefer-ip-address: true

aliyun:
  vod:
    file:
      keyid: keyid
      keysecret: keysecret
      regionId: cn-shanghai
