server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
aliyun:
  oss:
    file:
      endopint: endopint
      keyid: keyid
      keysecret: keysecret
      bucketname: bucketname
