server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
aliyun:
  oss:
    file:
      endopint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4G4XCkNTyRgPVR4QEdjT
      keysecret: 7nEi2YoeXQHcVQV2KRQkLSYxc9iIo6
      bucketname: guliedu-szf