server:
  port: 8006

spring:
  application:
    name: service-msm
  profiles:
    active: dev
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss            # springmvc对日期字符串的自动转换格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss            # 响应结果日期格式转换
    time-zone: GMT+8

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: service-msm:8006
    prefer-ip-address: true

# ribbon超时时间
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

---
spring:
  redis:
    host: 192.168.24.128
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0